application:
  port: 8000
  hmac_secret: "default-hmac-secret-oh-god-do-not-use-this-for-actual-purposes-just-for-testing"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "sample-token"
  timeout_milliseconds: 10000
